### ISSUE TITLE
.write_startup_file_Jon method isn't available with MTpy package 

### ISSUE THREAD

**Issue by aeh1707** [Jon-GSC/MT1D_CNN#2]
I had a problem running the data generation script where this attribute isn't available with Mtpy package, since it has Jon at the end I gueessed it would be a modified version by Jon the owner to this repo, please can help with this matter.

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/866da9af-6067-4014-a8bb-685264be5c06)

**Comment by Jon-GSC** [comment]
Hi,   This is a revised function based on 'write_starup_file' in mtpy package. Please find this function in file 'occam1d.py' and make a copy, then assign 'res_i' to 'start_rho' variable at the end.  Or you can write a function to write the model datasets.   Hope this is helpful.

**Comment by aeh1707** [comment]
Hi @Jon-GSC , thank you so much for your help and quick reply,

I done as you told me, I change the source code in the MTpy path for occam1d.py, and replaced the last occurrence of start_rho with resi_i in write_starup_file function, but I have got a new error.

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/d9838e37-de55-42c3-9166-87e52be63600)

This is the line I have change for your reference
![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/3207b81a-a141-459e-ad29-4bf8618f5a21)
![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/ea4d0cec-58a2-4ca0-b064-81d2337c01b5)

 It would be much helpful if you provided the whole revised modified function.

**Comment by Jon-GSC** [comment]
just need a tiny revision.
add:
     if res_i is not None:
         self.start_rho = res_i
before:
    for ii in range(model.num_params):
      ....

**Comment by aeh1707** [comment]
Hi @Jon-GSC 

I change it as you told me but still getting the error, could you please look up that modified function file for me, or join a quick call to resolve it? I would really appreciate it.

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/137bc6aa-138b-4de0-bbea-a12ffd0f97b4)

**Comment by Jon-GSC** [comment]
just checked, you can revise last part with following code, should work ok, let me know.
       if res_i is not None:  
            self.start_rho = res_i
        for ii in self.start_rho:  
            infid.write('{0}{1:.2f}\n'.format(self._ss, ii))
        # 
        #    for ii in range(model.num_params):
        #        infid.write('{0}{1:.2f}\n'.format(self._ss,
        #                                          np.log10(self.start_rho)))
        infid.close()

**Comment by aeh1707** [comment]
Hi @Jon-GSC 

Another error showed,

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/ea8b6a13-f825-44de-91a6-e849c9bd08eb)

in the function write_startup_file_Jon there's another paramater for path, I think saving the files names isn't working well

Could you copy paste the whole modified function here?? I have been going at it all day, it makes me real tired 😆

**Comment by Jon-GSC** [comment]
looks the write_startup__ function works ok now.  You need check the Occam1d forward result. The error shows the response data is missing.

**Comment by aeh1707** [comment]
Okay, write_start_file is working after I added the the save_fn param which as missing before

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/42ad6351-1183-4ab7-ba36-73bf78b912a9)

I commented the two lines of moving the resulted files to their folder just to see what files are being generated

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/170f3729-6275-4293-b11e-ef70636a9061)

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/3cf19819-5336-49bb-9ed3-0aa259903974)

You can see startup files are generated fine, but I dont any result for the forward process that is done by Occam
![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/6c5f92bf-f516-46a3-972b-1467bcc92475)

What might be the reason for this? and what should I check, I'm running this on linux ubuntu, it should work without any setup for Occam.

**Comment by Jon-GSC** [comment]
Hi, you need read the Occam manual to check if you set the path etc. correctly, make sure the Occam runs the forward and generates the response files. Normally the output filename is 'occam1D_*_*.resp'.

**Comment by aeh1707** [comment]
Thank you so much @Jon-GSC , your help and prompt reply was very helpful, now it runs smoothly.
