### ISSUE TITLE
Can Not Find Attribute 'savgol_smooth_Jon_3'

### ISSUE THREAD

**Issue by aeh1707** [Jon-GSC/MT1D_CNN#3]
Hi @Jon-GSC ,

I tried running forWeb3_Prediction.py but I got the following error as in the picture, I looked in the "forWeb_cnn_1D.py" but couldn't find the function savgol_smooth_Jon_3 , however I found a similar one called savgol_smooth_Jon, I tried it but also received an error I guess mabe you had different versions for it, could you please sharing the working function with number 3 at its end.

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/fd314165-f620-432a-96e5-92d4b1109918)

The error received after using savgol_smooth_Jon:

![image](https://github.com/Jon-GSC/MT1D_CNN/assets/95165255/199036ef-309d-4866-8ea2-bc6f0d554ade)

**Comment by Jon-GSC** [comment]
Hi, I am not sure this error. Looks like I used this for testing noise and other data sets. You can just ignore this function during model training. For prediction, you can delete savgol_smooth_Jon_1,2,3.. then plot predicted result directly. 
I will be back in office in January, will check the functions if you still haven't solve this error..
